const fs = require('fs');
const out = 'c:/Users/BigEP/OneDrive/Documents/GitHub/midas/server/router.js';

let c = '';
function add(s) { c += s + '\n'; }

add("function browseHandler(req, res, targetUrl, depth = 0) {");
add("  const sid = getOrCreateSid(req, res);");
add("  const jar = jarFor(sid);");
add("");
add("  let url;");
add("  try { url = new URL(targetUrl); } catch {");
add("    res.writeHead(400, { 'content-type': 'text/plain' }); res.end('bad url'); return;");
add("  }");
add("  if (url.protocol !== 'http:' && url.protocol !== 'https:') {");
add("    res.writeHead(400, { 'content-type': 'text/plain' }); res.end('unsupported protocol'); return;");
add("  }");
add("");
add("  const reqUrl = new URL(req.url, 'http://x');");
add("  for (const [k, v] of reqUrl.searchParams) {");
add("    if (k === 'url') continue;");
add("    url.searchParams.append(k, v);");
add("  }");
add("");
add("  const isHttps = url.protocol === 'https:';");
add("  const lib = isHttps ? https : http;");
add("");
add("  const headers = {};");
add("  headers['user-agent'] = req.headers['user-agent'] || 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';");
add("  headers['accept'] = req.headers['accept'] || 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8';");
add("  headers['accept-language'] = req.headers['accept-language'] || 'en-US,en;q=0.9';");
add("  headers['accept-encoding'] = 'gzip, deflate, br';");
add("  headers['sec-ch-ua'] = req.headers['sec-ch-ua'] || '\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"125\", \"Google Chrome\";v=\"125\"';");
add("  headers['sec-ch-ua-mobile'] = req.headers['sec-ch-ua-mobile'] || '?0';");
add("  headers['sec-ch-ua-platform'] = req.headers['sec-ch-ua-platform'] || '\"Windows\"';");
add("  headers['sec-fetch-dest'] = req.headers['sec-fetch-dest'] || 'document';");
add("  headers['sec-fetch-mode'] = req.headers['sec-fetch-mode'] || 'navigate';");
add("  headers['sec-fetch-site'] = req.headers['sec-fetch-site'] || 'none';");
add("  headers['sec-fetch-user'] = req.headers['sec-fetch-user'] || '?1';");
add("  headers['upgrade-insecure-requests'] = '1';");
add("  headers['cache-control'] = req.headers['cache-control'] || 'max-age=0';");
add("  if (req.headers['content-type']) headers['content-type'] = req.headers['content-type'];");
add("");
add("  const clientIp = req.headers['x-forwarded-for'] || req.headers['x-real-ip'] || req.socket?.remoteAddress || '';");
add("  if (clientIp) {");
add("    headers['x-forwarded-for'] = clientIp;");
add("    headers['x-real-ip'] = clientIp.split(',')[0].trim();");
add("  }");
add("");
add("  const refOriginal = extractOriginalFromProxy(req.headers.referer || '');");
add("  if (refOriginal) headers['referer'] = refOriginal;");
add("");
add("  const cookieHeader = buildCookieHeader(jar, url.hostname, url.pathname, isHttps);");
add("  if (cookieHeader) headers['cookie'] = cookieHeader;");
add("");
add("  const isCaptchaRequest = isCaptchaUrl(targetUrl);");
add("  if (isCaptchaRequest) {");
add("    Object.assign(headers, buildPassthroughHeaders(req.headers, targetUrl));");
add("  }");
add("");
add("  const options = {");
add("    hostname: url.hostname,");
add("    port: url.port || (isHttps ? 443 : 80),");
add("    path: url.pathname + url.search,");
add("    method: req.method,");
add("    headers,");
add("    rejectUnauthorized: false,");
add("  };");
add("");
add("  const proxyReq = lib.request(options, (proxyRes) => {");
add("    storeCookies(jar, url.hostname, proxyRes.headers['set-cookie']);");
add("");
add("    if ([301, 302, 303, 307, 308].includes(proxyRes.statusCode) && proxyRes.headers.location && depth < 8) {");
add("      const next = resolveUrl(url.toString(), proxyRes.headers.location);");
add("      proxyRes.resume();");
add("      if (next) {");
add("        if (req.method === 'GET' || req.method === 'HEAD') {");
add("          browseHandler(req, res, next, depth + 1);");
add("          return;");
add("        }");
add("        res.writeHead(302, { location: toProxyUrl(next), 'cache-control': 'no-store' });");
add("        res.end();");
add("        return;");
add("      }");
add("    }");
add("");
add("    const ct = (proxyRes.headers['content-type'] || '').toLowerCase();");
add("    const charsetMatch = ct.match(/charset=([^\\s;]+)/i);");
add("    const charset = charsetMatch ? charsetMatch[1] : 'utf-8';");
add("");
add("    const outHeaders = { ...proxyRes.headers };");
add("    delete outHeaders['content-security-policy'];");
add("    delete outHeaders['content-security-policy-report-only'];");
add("    delete outHeaders['strict-transport-security'];");
add("    delete outHeaders['x-frame-options'];");
add("    delete outHeaders['content-length'];");
add("    delete outHeaders['content-encoding'];");
add("    delete outHeaders['transfer-encoding'];");
add("    delete outHeaders['set-cookie'];");
add("    delete outHeaders['alt-svc'];");
add("    delete outHeaders['cross-origin-opener-policy'];");
add("    delete outHeaders['cross-origin-embedder-policy'];");
add("    delete outHeaders['cross-origin-resource-policy'];");
add("    delete outHeaders['origin-agent-cluster'];");
add("    delete outHeaders['permissions-policy'];");
add("    outHeaders['cache-control'] = 'no-store';");
add("");
add("    const enc = (proxyRes.headers['content-encoding'] || '').toLowerCase();");
add("    let stream = proxyRes;");
add("    if (enc === 'gzip') stream = proxyRes.pipe(zlib.createGunzip());");
add("    else if (enc === 'deflate') stream = proxyRes.pipe(zlib.createInflate());");
add("    else if (enc === 'br') stream = proxyRes.pipe(zlib.createBrotliDecompress());");
add("");
add("    const isHtml = ct.includes('text/html') || ct.includes('application/xhtml');");
add("    const isCss = ct.includes('text/css');");
add("    const isJs = ct.includes('javascript') || ct.includes('/ecmascript');");
add("    const isJson = ct.includes('application/json');");
add("");
add("    if (isCaptchaRequest && !isHtml) {");
add("      res.writeHead(proxyRes.statusCode, outHeaders);");
add("      stream.pipe(res);");
add("      return;");
add("    }");
add("");
add("    if (isHtml || isCss || isJs || isJson) {");
add("      const chunks = [];");
add("      stream.on('data', c => chunks.push(c));");
add("      stream.on('error', () => { if (!res.headersSent) { res.writeHead(502); res.end('decode error'); } });");
add("      stream.on('end', () => {");
add("        const buf = Buffer.concat(chunks);");
add("        const text = decodeBody(buf, charset);");
add("        const baseProxyUrl = '/_midas/' + currentPaths.browse;");
add("        let out = text;");
add("");
add("        if (isHtml) {");
add("          out = rewriteHtml(text, url.toString(), baseProxyUrl);");
add("          outHeaders['content-type'] = 'text/html; charset=utf-8';");
add("        } else if (isCss) {");
add("          out = rewriteCss(text, url.toString());");
add("          outHeaders['content-type'] = 'text/css; charset=utf-8';");
add("        } else if (isJs) {");
add("          out = rewriteJs(text, url.toString());");
add("          outHeaders['content-type'] = ct || 'application/javascript; charset=utf-8';");
add("        } else if (isJson) {");
add("          out = text.replace(/\"(https?:\\/\\/[^\"]+)\"/g, (m, u) => {");
add("            if (isAlreadyProxied(u) || isCaptchaUrl(u)) return m;");
add("            return '\"' + toProxyUrl(u) + '\"';");
add("          });");
add("        }");
add("");
add("        res.writeHead(proxyRes.statusCode, outHeaders);");
add("        res.end(out);");
add("      });");
add("    } else {");
add("      res.writeHead(proxyRes.statusCode, outHeaders);");
add("      stream.pipe(res);");
add("    }");
add("  });");
add("");
add("  proxyReq.on('error', () => {");
add("    if (!res.headersSent) {");
add("      res.writeHead(502, { 'content-type': 'text/plain' });");
add("      res.end('proxy error');");
add("    }");
add("  });");
add("");
add("  if (req.method !== 'GET' && req.method !== 'HEAD') {");
add("    req.pipe(proxyReq);");
add("  } else {");
add("    proxyReq.end();");
add("  }");
add("}");
add("");

fs.appendFileSync(out, c);
console.log('Part 7 done');

