const fs = require('fs');
const out = 'c:/Users/BigEP/OneDrive/Documents/GitHub/midas/server/router.js';

let c = '';
function add(s) { c += s + '\n'; }

add("export function router(req, res, url) {");
add("  setCors(res);");
add("");
add("  if (req.method === 'OPTIONS') {");
add("    res.writeHead(204); res.end(); return;");
add("  }");
add("");
add("  const pathname = url.pathname;");
add("  const pathType = matchPolymorphicPath(pathname, currentPaths);");
add("");
add("  if (pathname === '/_midas/session') {");
add("    const sid = generateSessionId();");
add("    const transport = url.searchParams.get('t') || 'chunked';");
add("    ACTIVE_TRANSPORTS.set(sid, { transport, created: Date.now() });");
add("    res.writeHead(200, { 'content-type': 'application/json' });");
add("    res.end(JSON.stringify({");
add("      sid,");
add("      transport,");
add("      nonce: Math.random().toString(36).slice(2),");
add("      paths: currentPaths,");
add("    }));");
add("    return;");
add("  }");
add("");
add("  if (pathType === 'noise') {");
add("    const size = 100 + Math.floor(Math.random() * 900);");
add("    const noise = Buffer.alloc(size);");
add("    for (let i = 0; i < size; i++) noise[i] = Math.floor(Math.random() * 256);");
add("    res.writeHead(200, {");
add("      'content-type': 'application/octet-stream',");
add("      'content-length': size,");
add("      'cache-control': 'no-store',");
add("    });");
add("    res.end(noise);");
add("    return;");
add("  }");
add("");
add("  if (pathType === 'browse') {");
add("    const target = url.searchParams.get('url');");
add("    if (!target) { res.writeHead(400); res.end('missing url'); return; }");
add("    browseHandler(req, res, target);");
add("    return;");
add("  }");
add("");
add("  if (pathType === 'stream') {");
add("    const sid = url.searchParams.get('sid');");
add("    if (!sid || !ACTIVE_TRANSPORTS.has(sid)) {");
add("      res.writeHead(400); res.end(); return;");
add("    }");
add("    res.writeHead(200, {");
add("      'content-type': 'text/event-stream',");
add("      'cache-control': 'no-cache',");
add("      'connection': 'keep-alive',");
add("    });");
add("    res.write(':ok\\n\\n');");
add("    const interval = setInterval(() => {");
add("      if (res.writableEnded) { clearInterval(interval); return; }");
add("      res.write(':ping\\n\\n');");
add("    }, 30000);");
add("    req.on('close', () => clearInterval(interval));");
add("    return;");
add("  }");
add("");
add("  if (pathType === 'proxy') {");
add("    const target = url.searchParams.get('url');");
add("    if (!target) { res.writeHead(400); res.end(); return; }");
add("    proxyRequest(req, res, target).catch(() => {");
add("      if (!res.headersSent) { res.writeHead(502); res.end(); }");
add("    });");
add("    return;");
add("  }");
add("");
add("  if (pathType === 'fetch') {");
add("    let body = '';");
add("    req.on('data', chunk => body += chunk);");
add("    req.on('end', async () => {");
add("      try {");
add("        const data = JSON.parse(body);");
add("        const target = data.url;");
add("        if (!target) { res.writeHead(400); res.end(); return; }");
add("");
add("        const targetUrl = new URL(target);");
add("        const lib = targetUrl.protocol === 'https:' ? https : http;");
add("        const options = {");
add("          hostname: targetUrl.hostname,");
add("          port: targetUrl.port || (targetUrl.protocol === 'https:' ? 443 : 80),");
add("          path: targetUrl.pathname + targetUrl.search,");
add("          method: data.method || 'GET',");
add("          headers: { ...(data.headers || {}) },");
add("          rejectUnauthorized: false,");
add("        };");
add("");
add("        const proxyReq = lib.request(options, (proxyRes) => {");
add("          let responseBody = '';");
add("          proxyRes.setEncoding('utf8');");
add("          proxyRes.on('data', chunk => responseBody += chunk);");
add("          proxyRes.on('end', () => {");
add("            const outHeaders = { ...proxyRes.headers };");
add("            delete outHeaders['content-security-policy'];");
add("            delete outHeaders['content-security-policy-report-only'];");
add("            delete outHeaders['strict-transport-security'];");
add("            delete outHeaders['x-frame-options'];");
add("");
add("            res.writeHead(200, { 'content-type': 'application/json' });");
add("            res.end(JSON.stringify({");
add("              status: proxyRes.statusCode,");
add("              headers: outHeaders,");
add("              body: responseBody,");
add("            }));");
add("          });");
add("        });");
add("");
add("        proxyReq.on('error', () => {");
add("          if (!res.headersSent) {");
add("            res.writeHead(502, { 'content-type': 'application/json' });");
add("            res.end(JSON.stringify({ status: 502, headers: {}, body: '' }));");
add("          }");
add("        });");
add("");
add("        if (data.body && (data.method === 'POST' || data.method === 'PUT' || data.method === 'PATCH')) {");
add("          proxyReq.write(data.body);");
add("        }");
add("        proxyReq.end();");
add("      } catch (e) {");
add("        res.writeHead(400); res.end();");
add("      }");
add("    });");
add("    return;");
add("  }");
add("");
add("  if (pathType === 'chunk') {");
add("    let body = '';");
add("    req.on('data', chunk => body += chunk);");
add("    req.on('end', async () => {");
add("      try {");
add("        const data = JSON.parse(body);");
add("        const target = data.url;");
add("        if (!target) { res.writeHead(400); res.end(); return; }");
add("");
add("        const targetUrl = new URL(target);");
add("        const lib = targetUrl.protocol === 'https:' ? https : http;");
add("        const options = {");
add("          hostname: targetUrl.hostname,");
add("          port: targetUrl.port || (targetUrl.protocol === 'https:' ? 443 : 80),");
add("          path: targetUrl.pathname + targetUrl.search,");
add("          method: 'GET',");
add("          headers: { ...data.headers, 'accept': data.headers?.accept || '*/*' },");
add("          rejectUnauthorized: false,");
add("        };");
add("");
add("        const proxyReq = lib.request(options, (proxyRes) => {");
add("          res.writeHead(proxyRes.statusCode, {");
add("            'content-type': proxyRes.headers['content-type'] || 'application/octet-stream',");
add("            'transfer-encoding': 'chunked',");
add("          });");
add("          proxyRes.pipe(res);");
add("        });");
add("        proxyReq.on('error', () => { if (!res.headersSent) { res.writeHead(502); res.end(); } });");
add("        proxyReq.end();");
add("      } catch (e) {");
add("        res.writeHead(400); res.end();");
add("      }");
add("    });");
add("    return;");
add("  }");
add("");
add("  res.writeHead(404); res.end();");
add("}");
add("");

fs.appendFileSync(out, c);
console.log('Part 8 done - router complete');

