const fs = require('fs');
const out = 'c:/Users/BigEP/OneDrive/Documents/GitHub/midas/server/router.js';

let c = '';
function add(s) { c += s + '\n'; }

add("function proxyRequest(req, res, targetUrl, options = {}) {");
add("  return new Promise((resolve, reject) => {");
add("    const url = new URL(targetUrl);");
add("    const lib = url.protocol === 'https:' ? https : http;");
add("    const isPassthrough = options.passthrough || isCaptchaUrl(targetUrl);");
add("");
add("    const headers = options.headers || {};");
add("    if (isPassthrough) {");
add("      Object.assign(headers, buildPassthroughHeaders(req.headers, targetUrl));");
add("    }");
add("");
add("    delete headers['host'];");
add("    headers['host'] = url.host;");
add("");
add("    const reqOptions = {");
add("      hostname: url.hostname,");
add("      port: url.port || (url.protocol === 'https:' ? 443 : 80),");
add("      path: url.pathname + url.search,");
add("      method: options.method || req.method || 'GET',");
add("      headers,");
add("      rejectUnauthorized: false,");
add("    };");
add("");
add("    const proxyReq = lib.request(reqOptions, (proxyRes) => {");
add("      const outHeaders = { ...proxyRes.headers };");
add("      delete outHeaders['content-security-policy'];");
add("      delete outHeaders['content-security-policy-report-only'];");
add("      delete outHeaders['strict-transport-security'];");
add("      delete outHeaders['x-frame-options'];");
add("      delete outHeaders['set-cookie'];");
add("");
add("      if (isPassthrough) {");
add("        outHeaders['access-control-allow-origin'] = req.headers['origin'] || '*';");
add("        outHeaders['access-control-allow-credentials'] = 'true';");
add("      }");
add("");
add("      res.writeHead(proxyRes.statusCode, outHeaders);");
add("      proxyRes.pipe(res);");
add("      proxyRes.on('end', resolve);");
add("    });");
add("");
add("    proxyReq.on('error', (err) => {");
add("      if (!res.headersSent) {");
add("        res.writeHead(502, { 'content-type': 'text/plain' });");
add("        res.end('Proxy error');");
add("      }");
add("      reject(err);");
add("    });");
add("");
add("    if (options.body) {");
add("      proxyReq.write(options.body);");
add("      proxyReq.end();");
add("    } else if (req.method !== 'GET' && req.method !== 'HEAD') {");
add("      req.pipe(proxyReq);");
add("    } else {");
add("      proxyReq.end();");
add("    }");
add("  });");
add("}");
add("");

fs.appendFileSync(out, c);
console.log('Part 6 done');

