const fs = require('fs');
const out = 'c:/Users/BigEP/OneDrive/Documents/GitHub/midas/server/router.js';

let c = '';
function add(s) { c += s + '\n'; }

add("function parseCookieHeader(str) {");
add("  const out = {};");
add("  if (!str) return out;");
add("  for (const part of str.split(';')) {");
add("    const i = part.indexOf('=');");
add("    if (i < 0) continue;");
add("    out[part.slice(0, i).trim()] = part.slice(i + 1).trim();");
add("  }");
add("  return out;");
add("}");
add("");
add("function parseSetCookie(str) {");
add("  const parts = str.split(';').map(s => s.trim()).filter(Boolean);");
add("  if (!parts.length) return null;");
add("  const nv = parts.shift();");
add("  const eq = nv.indexOf('=');");
add("  if (eq < 0) return null;");
add("  const cookie = {");
add("    name: nv.slice(0, eq).trim(),");
add("    value: nv.slice(eq + 1).trim(),");
add("    path: '/',");
add("    domain: null,");
add("    expires: null,");
add("    secure: false,");
add("    httpOnly: false,");
add("  };");
add("  for (const a of parts) {");
add("    const ei = a.indexOf('=');");
add("    const k = (ei < 0 ? a : a.slice(0, ei)).trim().toLowerCase();");
add("    const v = ei < 0 ? '' : a.slice(ei + 1).trim();");
add("    if (k === 'path') cookie.path = v || '/';");
add("    else if (k === 'domain') cookie.domain = v.replace(/^\\./, '').toLowerCase();");
add("    else if (k === 'expires') { const t = Date.parse(v); if (t) cookie.expires = t; }");
add("    else if (k === 'max-age') { const n = parseInt(v, 10); if (!isNaN(n)) cookie.expires = Date.now() + n * 1000; }");
add("    else if (k === 'secure') cookie.secure = true;");
add("    else if (k === 'httponly') cookie.httpOnly = true;");
add("  }");
add("  return cookie;");
add("}");
add("");
add("function getOrCreateSid(req, res) {");
add("  const cookies = parseCookieHeader(req.headers.cookie);");
add("  let sid = cookies.midas_sid;");
add("  if (!sid) {");
add("    sid = generateSessionId();");
add("    const prev = res.getHeader('set-cookie');");
add("    const next = 'midas_sid=' + sid + '; Path=/; HttpOnly; SameSite=Lax';");
add("    res.setHeader('set-cookie', prev ? [].concat(prev, next) : next);");
add("  }");
add("  return sid;");
add("}");
add("");
add("function jarFor(sid) {");
add("  let j = COOKIE_JAR.get(sid);");
add("  if (!j) { j = new Map(); COOKIE_JAR.set(sid, j); }");
add("  return j;");
add("}");
add("");
add("function hostMatches(cookieHost, requestHost) {");
add("  if (!cookieHost) return true;");
add("  if (cookieHost === requestHost) return true;");
add("  return requestHost.endsWith('.' + cookieHost);");
add("}");
add("");
add("function buildCookieHeader(jar, hostname, pathname, isHttps) {");
add("  const out = [];");
add("  const now = Date.now();");
add("  for (const [host, list] of jar) {");
add("    if (!hostMatches(host, hostname)) continue;");
add("    for (const c of list) {");
add("      if (c.expires && c.expires < now) continue;");
add("      if (!pathname.startsWith(c.path)) continue;");
add("      if (c.secure && !isHttps) continue;");
add("      out.push(c.name + '=' + c.value);");
add("    }");
add("  }");
add("  return out.join('; ');");
add("}");
add("");
add("function storeCookies(jar, hostname, setCookieHeaders) {");
add("  if (!setCookieHeaders) return;");
add("  const list = Array.isArray(setCookieHeaders) ? setCookieHeaders : [setCookieHeaders];");
add("  for (const sc of list) {");
add("    const cookie = parseSetCookie(sc);");
add("    if (!cookie) continue;");
add("    const host = cookie.domain || hostname;");
add("    let bucket = jar.get(host);");
add("    if (!bucket) { bucket = []; jar.set(host, bucket); }");
add("    const idx = bucket.findIndex(c => c.name === cookie.name && c.path === cookie.path);");
add("    if (idx >= 0) bucket[idx] = cookie; else bucket.push(cookie);");
add("  }");
add("}");
add("");
add("function decodeBody(buf, charset) {");
add("  try { return new TextDecoder(charset || 'utf-8', { fatal: false }).decode(buf); }");
add("  catch { return buf.toString('utf8'); }");
add("}");
add("");

fs.appendFileSync(out, c);
console.log('Part 5 done');

