const fs = require('fs');
const out = 'c:/Users/BigEP/OneDrive/Documents/GitHub/midas/server/router.js';

let c = '';
function add(s) { c += s + '\n'; }

add(`function rewriteHtml(html, baseUrl, baseProxyUrl) {`);
add(`  html = html.replace(/<base\\b[^>]*>/gi, '');`);
add(``);
add(`  html = html.replace(/(<style\\b[^>]*>)([\\s\\S]*?)(<\\/style>)/gi,`);
add(`    (_m, open, body, close) => open + rewriteCss(body, baseUrl) + close);`);
add(``);
add(`  html = html.replace(/<meta\\s+http-equiv=["']?refresh["']?\\s+content=["']([^"']+)["'][^>]*>/gi,`);
add(`    (m, content) => {`);
add(`      const mm = content.match(/^\\s*([\\d.]+)\\s*;\\s*url\\s*=\\s*(.+?)\\s*$/i);`);
add(`      if (!mm) return m;`);
add(`      const abs = resolveUrl(baseUrl, mm[2]);`);
add(`      if (!abs) return m;`);
add(`      return m.replace(mm[2], toProxyUrl(abs));`);
add(`    });`);
add(``);
add(`  html = html.replace(`);
add(`    /\\b(href|src|action|formaction|poster|data)\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s>]+))/gi,`);
add(`    (m, attr, _all, dq, sq, uq) => {`);
add(`      const v = (dq ?? sq ?? uq ?? '').trim();`);
add(`      if (!v) return m;`);
add(`      if (/^(#|javascript:|data:|mailto:|blob:|tel:|about:|ws:|wss:)/i.test(v)) return m;`);
add(`      if (isAlreadyProxied(v)) return m;`);
add(`      const abs = resolveUrl(baseUrl, v);`);
add(`      if (!abs) return m;`);
add(`      return attr + '="' + toProxyUrl(abs) + '"';`);
add(`    }`);
add(`  );`);
add(``);
add(`  html = html.replace(/\\bsrcset\\s*=\\s*("([^"]*)"|'([^']*)')/gi, (m, _all, dq, sq) => {`);
add(`    const v = dq ?? sq ?? '';`);
add(`    const parts = v.split(',').map(p => {`);
add(`      const seg = p.trim().split(/\\s+/);`);
add(`      const u = seg[0];`);
add(`      if (!u || isAlreadyProxied(u) || /^data:/i.test(u)) return p;`);
add(`      const abs = resolveUrl(baseUrl, u);`);
add(`      if (!abs) return p;`);
add(`      seg[0] = toProxyUrl(abs);`);
add(`      return seg.join(' ');`);
add(`    });`);
add(`    return 'srcset="' + parts.join(', ') + '"';`);
add(`  });`);
add(``);
add(`  html = html.replace(/url\\(\\s*("([^"]*)"|'([^']*)'|([^)]*))\\)/gi, (m, _all, dq, sq, uq) => {`);
add(`    const v = (dq ?? sq ?? uq ?? '').trim();`);
add(`    if (!v || /^(data:|blob:|about:)/i.test(v) || isAlreadyProxied(v)) return m;`);
add(`    const abs = resolveUrl(baseUrl, v);`);
add(`    if (!abs) return m;`);
add(`    return 'url("' + toProxyUrl(abs) + '")';`);
add(`  });`);
add(``);
add(`  const stealthScript = getStealthScript(baseProxyUrl);`);
add(`  if (html.includes('</head>')) {`);
add(`    html = html.replace('</head>', stealthScript + '</head>');`);
add(`  } else if (html.includes('</body>')) {`);
add(`    html = html.replace('</body>', stealthScript + '</body>');`);
add(`  } else {`);
add(`    html += stealthScript;`);
add(`  }`);
add(``);
add(`  return html;`);
add(`}`);
add(``);

fs.appendFileSync(out, c);
console.log('Part 3 done');

